### ISSUE TITLE
Добавить районы в доставке

### ISSUE THREAD

**Issue by za78** [o-seer/sbormarket#13]
Мало районов в доставке

**Comment by o-seer** [comment]
Ждем перечень

**Comment by za78** [comment]
Список садоводств 
СНТ «Энергетик»
СНТ «Дружба»
СНТ «Березовая роща»
СНТ «Березовое»
ДНТ «Загородное»
СТ «Лесная поляна»
СНТ «Ручеек»
СНТ «Кедр»
СПС «Балтика»
ДНТ «Смолокурка»
СНТ «Смольненский»
СНТСН «Лотос»
ТСН «Престиж»
ДНТ «Бастион»
ДНТ «Молодежное»
СНТ «Эхо»
ДНТ «Эхо-2»
ДНТ «Звезда»
СНТ «Ветер»
ДНТ «Су-Псех»
СНТ «Ромашка»
ДНТ «Удача»
ДНТ «Медик»
ДНТ «Малахит»
СНТ «Березка»
СТСН «Новокалищенское»
СНТ «Новокалищенское-2»
СТ «Северное»
ДНТ «Весна»
НДО ПК «Семья»
СНТ «Южное»
ДНТ «Укрытие»
СНТ «Приозерное»
СНТ «Строитель»
СПК «Парус»
ТСН «Фортуна»
ДНТ «Северная Пальмира»
ТСН «Саванна»
СК «Надежда»
СПК «Ольха»
ТСН «Клен»
ТСН «Рябина»
СНТ «Пассаж»
ДНТ «Солнечное»
ДНТ «Заозерное»
ТСН «Балтийское»
ТСН «Рублевка»
ДНТ «Золотая долина»
СНТСН «Райское»
ДНТ «Удача-1»
ДНТСН «Приморский»
ДНТ «:Сосновка»
СНТ «Ручьи»
ДНТ «Ветеран»
ТСН «Чибис»
СНТ «Сосновое»
ДНТСН «Урожай»
ДНТ «Земляк»
ДНТ «Надежда»
ДНТ «Лесное»
ДНТ «Хутор»
ДНТ «Новое Керново»

**Comment by afa-spb** [comment]
Закрываю как ненужное
