### ISSUE TITLE
Создать раздел сайта - контакты

### ISSUE THREAD

**Issue by za78** [o-seer/sbormarket#14]
Добавить вкладку контакты

**Comment by afa-spb** [comment]
Что здесь должно быть?

**Comment by o-seer** [comment]
Должна быть яндекс карта с указанием адреса пункта выдачи

**Comment by za78** [comment]
59,8794931, 29,1486889

**Comment by za78** [comment]
https://maps.app.goo.gl/LBWHTD26V7DcUzcd8

**Comment by za78** [comment]
https://yandex.ru/navi/?whatshere%5Bpoint%5D=29.148788%2C59.879466&whatshere%5Bzoom%5D=18&lang=ru&from=navi

**Comment by za78** [comment]
N 59.879466 E 29.148788

**Comment by afa-spb** [comment]
сделано
