### ISSUE TITLE
Создать раздел сайта - условия доставки

### ISSUE THREAD

**Issue by za78** [o-seer/sbormarket#18]
И возможность корректировки погруп доставки и цен.
1. 100р
1. При заказе дапусти м от 1000р бесплатно
2. При заказе ТК(транспортной компании)

**Comment by o-seer** [comment]
Добавить раздел с условиями доставки. Нужно чтобы текст можно было менять в админ панели. Ждем текст раздела

**Comment by afa-spb** [comment]
сделано
