### ISSUE TITLE
Сделать поддержку подкатегорий

### ISSUE THREAD

**Issue by o-seer** [o-seer/sbormarket#5]
А мы можем сделать категории а внутри подкатегории?(или это очень круто)
Например:
1. "Продукты":
"аджика", "вода", "колбаса".
2. "Электрика":
 "кабели", "свет", "розетки"
3. "Автозапчасти":
"Передняя подвеска"
"Задняя подвеска"

**Comment by afa-spb** [comment]
Сделано
